### ISSUE TITLE
it works when commented "Require" line.

### ISSUE THREAD

**Issue by yasu47b** [ngyuki/zabbix-graph-viewer#1]
it works when commented "Require" line.

```
# Require all granted
```

My envs are bellow.
OS: CentOS release 6.6 (Final)
zabbix-server: v2.2.10 (revision 54806)
Apache/2.2.15 (Unix)

thanks your good tool!

**Comment by ngyuki** [comment]
Sorry, example configuration is intended for Apache 2.4.

Becomes as follows if Apache 2.2.

```
# >>> BEGIN YOUR APPEND
Alias /zabbix/view /path/to/zabbix-graph-viewer/html

<Directory "/path/to/zabbix-graph-viewer/html">
    Options all
    Order allow,deny
    Allow from all
</Directory>
# <<< END YOUR APPEND
```

Thank you for comment.

**Comment by yasu47b** [comment]
thanks it also works.
